/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'emilian' at '9/18/16 7:48 AM' with Gradle 3.0
 *
 * @author emilian, @date 9/18/16 7:48 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
